# Generated by Django 5.2.7 on 2025-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
